import os

fields = [
    "APP_NAME", "APP_VERSION", "DEBUG", "DATABASE_URL", "MONGODB_URL", "DB_NAME",
    "JWT_SECRET_KEY", "JWT_ALGORITHM", "ACCESS_TOKEN_EXPIRE_MINUTES", "REFRESH_TOKEN_EXPIRE_DAYS",
    "PASSWORD_MIN_LENGTH", "BCRYPT_ROUNDS", "CORS_ORIGINS", "RAZORPAY_KEY_ID", "RAZORPAY_KEY_SECRET",
    "RAZORPAY_WEBHOOK_SECRET", "WHATSAPP_BUSINESS_NUMBER", "UPLOAD_DIR", "MAX_UPLOAD_SIZE",
    "ALLOWED_IMAGE_EXTENSIONS", "DEFAULT_PAGE_SIZE", "MAX_PAGE_SIZE", "RATE_LIMIT_LOGIN",
    "RATE_LIMIT_REGISTER", "RATE_LIMIT_ORDER", "RATE_LIMIT_DEFAULT", "SMTP_HOST", "SMTP_PORT",
    "SMTP_USER", "SMTP_PASSWORD", "FROM_EMAIL"
]

for key in os.environ:
    if key in fields:
        print(f"Matched env var: {key}={os.environ[key]}")
